media_folder: media
submission_per_fetch: 15
default_tweet: Some animals for ya :3
fetch_limit: 20

logger: {
    file: '',
    name: default-log,
    file_level: 30,
    console_level: 30
}

banned_post: []

excluded_flair: 
    - Advise
    - Human

subreddits: {
    'cats': '',
    'aww': '',
    'DOG': '',
    'AnimalsBeingBros': '',
    'AnimalsBeingJerks': '',
    'PetsareAmazing': '',
    'sneks': '',
    'rarepuppers': '',
    'Eyebleach': '',
    'Kitten': '',
    'StartledCats': '',
    'AnimalsBeingGeniuses': '',
    'holdmycatnip': '',
    'woof_irl': '',
    'Zoomies': '',
    'husky': '',
    'curledfeetsies': '',
    'birding': '',
    'Rabbits': '',
    'foxes': '',
    'goldenretrievers': '',
    'dogpictures': '',
    'mlem': '',
    'catpictures': '',
    'lookatmydog': '',
    'trashpandas': '',
    'corgi': '',
    'hamsters': '',
    'Blep': '',
    'teefies': '',
    'jellybeantoes': '',
    'Catloaf': '',
    'WhatsWrongWithYourDog': '',
    'FunnyAnimals': ''
}