media_folder: media
submission_per_fetch: 15
default_tweet: Routine test! Improving the logging.
fetch_limit: 20

logger: {
    file: '',
    name: default-log,
    file_level: 30,
    console_level: 30
}

banned_post: []

excluded_flair: 
    - Advise
    - Human

subreddits: {
    cats: '',
    aww: ''
}